<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modelo de Caixas</title>
    <style>
        h1 {/* Box-Level */
            background-color: lightblue;
            height: 300px;
            width: 300px;

            /*border-width: 10px;
            border-style: solid;
            border-color: darkslategray;*/

            border: 10px solid darkslategray;

            /*padding-top: 10px;
            padding-right: 10px;
            padding-bottom: 10px;
            padding-left: 10px;*/

            padding: 10px;
            
            /*margin-top: 10px;
            margin-right: auto;
            margin-bottom: 40px;
            margin-left: auto;*/

            margin: 10px auto 40px auto;

            /*outline-width: 5px;
            outline-style: dashed;
            outline-color: salmon;*/

            outline: 5px dashed salmon;
        }

        a { /* Inline-Level */
            border-width: 10px;
            border-style: solid;
            border-color: red;
            padding: 10px;
        }
    </style>
</head>
<body>
    <h1>Exemplos de caixa Box-Level</h1>
    <p>Parágrafos também são exemplos de box-level, mas os <a href="#">links são exemplos de caixas inline-level</a>. Vamos ver como tudo isso funciona</p>
</body>
</html>

<!-- # Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 -->
